#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

bk_build_json() {
  curl -H "Authorization: Bearer $GITLAB_STATUS_PLUGIN_BUILDKITE_READ_BUILDS_TOKEN" \
    "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER"
}

bk_scheduled_jobs_name_url() {
  bk_build_json | jq -r '.jobs[] | select(.state == "scheduled") | "\(.name)\t\(.web_url)"'
}

echo "-- debug plugin"
set -x
bk_build_json

echo "-- setting gitlab commit status"

set_gitlab_state "running"

# set any scheduled jobs to pending in gitlab
while IFS=$'\t' read -r name url; do
  set_gitlab_state "pending" "$name" "$url"
done < <(bk_scheduled_jobs_name_url)
